version: '3.4'

services:
  juniorcake:
    image: juniorcake
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro